### PR TITLE
added more recipe data

### PR DESCRIPTION
**Pull request by Christianmsm**

### CODE REVIEW

**Review by CodeByDex — CHANGES_REQUESTED** [review]
So recipe does not actually contain a field called ingredients. 

this isn't causing an error because it's just being ignored.

to actually hydrate recipe ingredient we would need to:

1. Create a seed script for the Ingredient model
2. Create a separate seeds script that populates the RecipeIngredient model

**Review by that-devguy — APPROVED** [review]
Looks good!

**Review by ChelseaLuevano — APPROVED** [review]
These are hilarious recipes! 😆

**Review by Christianmsm — COMMENTED** [review]
Yay Ted's Biscuits

**Comment by Christianmsm** [comment]
Yay Ted's Biscuits 😂

**Review by ChelseaLuevano — APPROVED** [review]

**Review by CodeByDex — APPROVED** [review]

**Pull request merged**
